#ifndef __MEDIAFOUNDATION_WEBMMFTESTS_MFPLAY_MFPLAYER_MAIN_HPP__
#define __MEDIAFOUNDATION_WEBMMFTESTS_MFPLAY_MFPLAYER_MAIN_HPP__

void ShowErrorMessage(PCWSTR format, HRESULT hrErr);

#endif // __MEDIAFOUNDATION_WEBMMFTESTS_MFPLAY_MFPLAYER_MAIN_HPP__
